PREFIX ?= /usr/local
BINDIR  = $(DESTDIR)$(PREFIX)/bin
SET    ?= bash

all:
	@echo "targets: install uninstall test check   (SET=bash|zsh|ash|powershell)"

install:
	install -d $(BINDIR)
	install -m 0755 $(SET)/hget $(SET)/hexec $(SET)/hwait $(SET)/hmirror $(BINDIR) 2>/dev/null || \
	install -m 0755 $(SET)/hget.ps1 $(SET)/hexec.ps1 $(SET)/hwait.ps1 $(SET)/hmirror.ps1 $(BINDIR)

uninstall:
	rm -f $(BINDIR)/hget $(BINDIR)/hexec $(BINDIR)/hwait $(BINDIR)/hmirror
	rm -f $(BINDIR)/hget.ps1 $(BINDIR)/hexec.ps1 $(BINDIR)/hwait.ps1 $(BINDIR)/hmirror.ps1

portable:
	@printf '#!/bin/bash\n# 2026 Remco van Mook @rvmnl - Apache-2.0 - github.com/remcovanmook/notcurl\n# hget - one file that runs as a shell script on Unix and as a\n# PowerShell script on Windows. Generated by "make portable"; edit\n# bash/hget or powershell/hget.ps1, not this. See portable/README.md.\n#\n#   ./hget.ps1 URL        (Unix: the shebang wins, the extension is ignored)\n#   .\\hget.ps1 URL        (Windows PowerShell)\n\nfunction choose\n{\neval "$$(sed -n %s "$$0")"\nexit\n}\n' "'s/^#://p'" > portable/hget.ps1
	@{ tail -n +2 bash/hget; printf 'exit\n'; } | sed 's/^/#:/' >> portable/hget.ps1
	@printf '$${true:-choose "$$@"}\nfunction choosetrue\n{\n' >> portable/hget.ps1
	@tail -n +2 powershell/hget.ps1 >> portable/hget.ps1
	@printf '\n}\n& "choose$$true" @args\n' >> portable/hget.ps1
	@chmod +x portable/hget.ps1
	@printf 'portable/hget.ps1: %s bytes\n' "$$(wc -c < portable/hget.ps1 | tr -d ' ')"

test:
	./test.sh

check:
	HGET_NET=1 ./test.sh

.PHONY: all install uninstall portable test check
